# NUMPY (continues)

In [1]:
import numpy as np

## comparison and masking

In [2]:
#comparing operations between arrays
a=np.array([1,3,4])
b=np.array([2,2,7])
c = a < b
print(c)

[ True False  True]


In [3]:
print(c.all())   # were all True
print(c.any())   # was some comparison True

False
True


In [4]:
#number of comparisons that are True
print(np.sum(c))

2


In [5]:
#broadcasting can also be applied to comparison
print(a > 0)

[ True  True  True]


In [6]:
##try some operations on real data: frist, obtain the data from a weather station

In [7]:
import pandas as pd
a=pd.read_csv("https://raw.githubusercontent.com/csmastersUH/data_analysis_with_python_2020/master/kumpula-weather-2017.csv")['Air temperature (degC)'].values

In [8]:
a

array([  0.6,  -3.9,  -6.5, -12.8, -17.8, -17.8,  -3.8,  -0.5,   0.5,
         1.7,  -1.6,  -2.8,   1.1,   0.8,  -2.8,  -4.2,  -3.5,   1.1,
         1.6,  -0.6,  -1.8,   1. ,   0.1,  -2.2,  -3.8,   1.9,   1.6,
         0.8,   0.6,   1. ,   0.2,  -0.6,  -0.8,  -0.2,   0.4,  -2.5,
        -7.3, -12.1,  -8.8, -10.1,  -8.3,  -5.4,  -2.7,   1.5,   4.4,
         0. ,   0.5,   1.5,   1.9,   2.2,   0.4,  -2.5,  -4.6,  -0.7,
        -5.3,  -5.6,  -2. ,  -2.3,   2.1,   1.5,   1.5,   0.9,  -1.8,
        -4.2,  -4.2,  -2.9,   0.2,   1.2,   1.4,   2.2,  -0.9,   0.6,
         0.6,   3.8,   3.4,   2. ,   1.6,   0.6,   0.2,   1.6,   2.3,
         2.5,   0.5,   1.9,   4.8,   6.6,   2.4,   0.4,  -0.4,   0.2,
         1.5,   4.3,   3. ,   3.8,   3.3,   4.7,   4.1,   3.3,   3.7,
         6. ,   4.3,   1.8,   1.2,  -0.5,  -1.4,  -1.7,   0.6,   0.3,
         1.2,   2.5,   5.7,   3.1,   2.9,   3.6,   2.8,   3.2,   4.4,
         4.1,   2.3,   2.2,   7.6,   9.4,   9.2,   6.7,  10.1,  11.1,
         6.1,   4.4,

In [9]:
print("Number of days with the temperature below zero:", np.sum(a < 0))

Number of days with the temperature below zero: 49


In [10]:
#In core Python we can combine truth values using the and, or, and not keywords. For boolean array however we have to use the elementwise operators &, |, and ~, respectively
np.sum((0 < a) & (a < 10))     # Temperature is greater than 0 and less that 10
#you need to use parantheses between the comparisons, because the precedent & is higher than <

185

In [11]:
#another use of boolean arrays: masking
c = a > 0
print(c[:10])    # print only the first ten elements
print(a[c])      # Select only the positive temperatures

[ True False False False False False False False  True  True]
[ 0.6  0.5  1.7  1.1  0.8  1.1  1.6  1.   0.1  1.9  1.6  0.8  0.6  1.
  0.2  0.4  1.5  4.4  0.5  1.5  1.9  2.2  0.4  2.1  1.5  1.5  0.9  0.2
  1.2  1.4  2.2  0.6  0.6  3.8  3.4  2.   1.6  0.6  0.2  1.6  2.3  2.5
  0.5  1.9  4.8  6.6  2.4  0.4  0.2  1.5  4.3  3.   3.8  3.3  4.7  4.1
  3.3  3.7  6.   4.3  1.8  1.2  0.6  0.3  1.2  2.5  5.7  3.1  2.9  3.6
  2.8  3.2  4.4  4.1  2.3  2.2  7.6  9.4  9.2  6.7 10.1 11.1  6.1  4.4
  1.5  1.5  2.9  5.1  7.5  9.8  9.   7.3  9.4 11.2 16.1 16.9 14.7 14.6
 13.3 12.4 14.1 14.1  9.6 13.2 14.1  9.6 10.8  6.5  6.2 10.   9.9 10.4
 14.5 16.4 12.3 14.  16.3 16.8 12.6 12.6 14.8 15.1 18.4 19.3 16.9 17.8
 12.7 12.4 12.2 10.8 12.9 14.  13.5 13.7 15.3 16.3 17.2 14.1 16.4 14.5
 14.1 14.  11.5 14.7 16.1 17.4 18.  16.8 16.8 14.7 15.3 16.7 18.  15.4
 15.  13.7 14.6 15.8 15.6 16.9 15.7 16.1 17.2 19.  19.1 17.8 18.3 17.8
 18.9 17.5 18.2 16.6 17.1 16.  15.2 17.2 18.3 18.7 18.1 19.6 17.4 16.1
 16.4 17.6 19.  

In [12]:
a #the array before prints the condition c (the values of the array need to be above 0)

array([  0.6,  -3.9,  -6.5, -12.8, -17.8, -17.8,  -3.8,  -0.5,   0.5,
         1.7,  -1.6,  -2.8,   1.1,   0.8,  -2.8,  -4.2,  -3.5,   1.1,
         1.6,  -0.6,  -1.8,   1. ,   0.1,  -2.2,  -3.8,   1.9,   1.6,
         0.8,   0.6,   1. ,   0.2,  -0.6,  -0.8,  -0.2,   0.4,  -2.5,
        -7.3, -12.1,  -8.8, -10.1,  -8.3,  -5.4,  -2.7,   1.5,   4.4,
         0. ,   0.5,   1.5,   1.9,   2.2,   0.4,  -2.5,  -4.6,  -0.7,
        -5.3,  -5.6,  -2. ,  -2.3,   2.1,   1.5,   1.5,   0.9,  -1.8,
        -4.2,  -4.2,  -2.9,   0.2,   1.2,   1.4,   2.2,  -0.9,   0.6,
         0.6,   3.8,   3.4,   2. ,   1.6,   0.6,   0.2,   1.6,   2.3,
         2.5,   0.5,   1.9,   4.8,   6.6,   2.4,   0.4,  -0.4,   0.2,
         1.5,   4.3,   3. ,   3.8,   3.3,   4.7,   4.1,   3.3,   3.7,
         6. ,   4.3,   1.8,   1.2,  -0.5,  -1.4,  -1.7,   0.6,   0.3,
         1.2,   2.5,   5.7,   3.1,   2.9,   3.6,   2.8,   3.2,   4.4,
         4.1,   2.3,   2.2,   7.6,   9.4,   9.2,   6.7,  10.1,  11.1,
         6.1,   4.4,

### exercise 1: column comparison

In [13]:
def column_comparison(a):
    a_1 = a[:, -2 ]
    a_2 = a[:, 1 ]
    c = a_1 < a_2
    return a[c]

In [14]:
a = 

In [15]:
column_comparison(a)

array([[8, 9, 3, 8, 8],
       [5, 7, 6, 0, 4],
       [7, 8, 1, 6, 2]])

### exercise 2: first half second half

In [88]:
def first_half_second_half(a): 
    num_cols = a.shape[1]
    num = int(num_cols/2)
    first_half = (np.sum(a[:, :num], axis=1))
    second_half = (np.sum(a[:, num:], axis=1))
    c = (first_half) > (second_half)
    return a[c]

In [89]:
a = np.array([[ 0.35180586,  1.88983976 , 1.49042416 , 0.64525458],
 [-0.13993531, -1.01939481, -0.43033861 , 1.09819521],
 [ 0.45711462 , 0.55860704,  0.41329038 ,-1.17269951],
 [-0.45337302 , 0.47335851,  0.33988828 ,-0.33855761],
 [-0.10105288 , 0.95725541, -0.4616711  ,-0.40969006],
 [ 0.30602722 , 0.23859857, -1.23968771 , 1.08038802],
 [ 1.7395324  ,-0.13637032,  0.47784971 ,-2.89645514],
 [-0.3445434  ,-1.21550912, -0.33752912 , 0.86132522],
 [ 0.35661489 , 0.9527794 ,  1.2638403 ,  0.25742605],
 [ 0.63837386 , 1.29454589, -0.91974513, -0.36121907]])

In [90]:
first_half_second_half(a)
#array([[2, 2, 1, 2]])

array([[ 0.35180586,  1.88983976,  1.49042416,  0.64525458],
       [ 0.45711462,  0.55860704,  0.41329038, -1.17269951],
       [-0.45337302,  0.47335851,  0.33988828, -0.33855761],
       [-0.10105288,  0.95725541, -0.4616711 , -0.40969006],
       [ 0.30602722,  0.23859857, -1.23968771,  1.08038802],
       [ 1.7395324 , -0.13637032,  0.47784971, -2.89645514],
       [ 0.63837386,  1.29454589, -0.91974513, -0.36121907]])

## Fancy indexing

In [91]:
#for getting multiple elemets, not necessary contigious, you need to have to index several times
np.random.seed(0)
a=np.random.randint(0, 20,20)
a2=np.array([a[2], a[5], a[7]])
print(a)
print(a2)

[12 15  0  3  3  7  9 19 18  4  6 12  1  6  7 14 17  5 13  8]
[ 0  7 19]


In [92]:
##fancy indexing
idx=[2,5,7]           # List of indices
print(a[idx])         # In fancy indexing in place of a single index, we can provide a list of indices
print(a[[2,5,7]])     # Or directly

[ 0  7 19]
[ 0  7 19]


In [93]:
#you can access multiple elements with fancy indexing
a[idx] = -1
print(a)

[12 15 -1  3  3 -1  9 -1 18  4  6 12  1  6  7 14 17  5 13  8]


In [94]:
#it also worrks in higher dimension arrays
b=np.arange(16).reshape(4,4)
print(b)
row=np.array([0,2])
col=np.array([1,3])
print(b[row, col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1 11]


In [95]:
#the shape of the result array is defined by the shape of the index array, not the original array:
row2=np.array([[0, 0], [2,2]])
col2=np.array([[1,3], [1,3]])
print(row2)
print(col2)
print(b[row2, col2])

[[0 0]
 [2 2]]
[[1 3]
 [1 3]]
[[ 1  3]
 [ 9 11]]


In [96]:
#for repetition and not having to write all the indices, we can use broadcasting:
row2=row.reshape(2,1)   # has shape (2, 1)
col2=col.reshape(1,2)   # has shape (1, 2)
print(row2)
print(col2)
print(b[row2, col2])    # the index arrays will be broadcasted here to shape (2,2)

[[0]
 [2]]
[[1 3]]
[[ 1  3]
 [ 9 11]]


In [97]:
# sllicing, normal nad fancy indexing can be combined
b[:,[0,2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])