# Python continues
## Regular expression
### Examples

In [1]:
a = "Apple"
import re
re.match(r"[Aa]pple", a)

<re.Match object; span=(0, 5), match='Apple'>

### Match and search functions

In [2]:
#import re
s = "Doing things, going home, staying awale, sleeping later" 
re.findall(r'\w+ing\b',s)

['Doing', 'going', 'staying', 'sleeping']

In [3]:
re.findall(r'[+-]?\d+', "23 +-24 = -1")

['23', '-24', '-1']

In [4]:

s = ("If I’m not in a hurry, then I should stay. " +
    "On the other hand, if I leave, then I can sleep.")
re.findall(r'[Ii]f (.*), then', s)

['I’m not in a hurry, then I should stay. On the other hand, if I leave']

In [5]:
import re
str = """He is the president of Russia.
He’s a powerful man."""
newstr = re.sub(r'(\b[Hh]e\b)', r'\1 (Putin)', str, 1)
print (newstr)

He (Putin) is the president of Russia.
He’s a powerful man.


## exercise01

In [6]:
'[+]?\b\d+' #66%

'[+]?\x08\\d+'

In [7]:
import re 
def integers_in_brackets(s):
    L = []
    L = re.findall(r'[+-]\b\d+', s)
    L = list(map(int, L))
    return L

In [8]:
def integers_in_brackets(s):
    aux = []
    for l in re.findall(r'\[\s*[+-]?\b\d+\b\s*\]',s):
        for x in re.findall(r'[+-]?\b\d+\b',l):
            aux.append(int(x))
    return aux

In [9]:
integers_in_brackets("  afd [asd] [12 ] [a34]  [ -43 ]tt [+12]xxx")
#[12, -43, 12]

[12, -43, 12]

In [10]:
integers_in_brackets("afd [128+] [47 ] [a34]  [ +-43 ]tt [+12]xxx!")
# [47, 12]

[47, 12]

In [11]:
s = "afd [128+] [47 ] [a34]  [ +-43 ]tt [+12]xxx!"
re.findall(r"\b\w+",s)

['afd', '128', '47', 'a34', '43', 'tt', '12', 'xxx']

## exercise 02

In [12]:
def file_listing(filename):
    text = open(filename, mode='r')
    L = []
    for i in text:
        line = text.readline()
        line = re.findall(r'\b\S+', line)
        #line = re.search(r'.{30}\s+(\d+)\s(\S+)\s(..)\s(\d+):(\d+)\s(.*)', text)
        line = tuple(line)
        L.append(line)
        #for line in re.finditer(L, text)
    return L

In [13]:
def file_listing(filename):
    tulos = []
    with open(filename, "r") as f:
        for x in range(47):
            tmp = []
            line = f.readline()
            mo = re.search(r'.{30}\s+(\d+)\s(\S+)\s(..)\s(\d+):(\d+)\s(.*)', line)
            for i in range(1, 7):
                try:
                    tmp.append(int(mo.group(i)))
                except ValueError:
                    tmp.append(mo.group(i))
                tupla = tuple(tmp)
            tulos.append(tupla)
    return tulos

In [14]:
tulos = []
with open('listing.txt', "r") as f:
    for x in range(47):
        tmp = []
        line = f.readline()
        mo = re.search(r'.{30}\s+(\d+)\s(\S+)\s(..)\s(\d+):(\d+)\s(.*)', line)
        for i in range(1, 7):
            try:
                tmp.append(int(mo.group(i)))
            except ValueError:
                tmp.append(mo.group(i))
            tupla = tuple(tmp)
        tulos.append(tupla)
tulos

[(2356, 'Dec', 11, 11, 50, 'add_colab_link.py'),
 (164519, 'Dec', 28, 17, 59, 'basics.ipynb'),
 (164477, 'Nov', 5, 19, 21, 'basics.ipynb.orig'),
 (115587, 'Dec', 11, 11, 50, 'bayes.ipynb'),
 (4096, 'Nov', 29, 13, 7, '_build'),
 (198820, 'Dec', 11, 11, 50, 'clustering.ipynb'),
 (6647, 'Dec', 11, 12, 20, 'conf.py'),
 (41828, 'Nov', 28, 13, 26, 'example_figure2.png'),
 (125079, 'Nov', 28, 13, 26, 'example_figure2.xcf'),
 (24139, 'Nov', 28, 12, 3, 'example_figure.png'),
 (650, 'Nov', 28, 12, 3, 'example_figure.py'),
 (25399, 'Nov', 2, 21, 25, 'exception_hierarchy.pdf'),
 (43632, 'Nov', 2, 22, 5, 'exception_hierarchy.png'),
 (24366, 'Nov', 2, 21, 26, 'exception_hierarchy.svg'),
 (72095, 'Oct', 3, 17, 36, 'extra.ipynb'),
 (1207075, 'Nov', 28, 16, 2, 'face.png'),
 (897, 'Nov', 12, 10, 59, 'generate_contents.py'),
 (4096, 'Dec', 27, 13, 55, '.git'),
 (19, 'Dec', 10, 10, 24, '.gitignore'),
 (890349, 'Dec', 11, 11, 50, 'image_processing.ipynb'),
 (689, 'Dec', 10, 10, 28, 'index.rst'),
 (5254, 'N

In [84]:
file_listing('listing.txt')
#(25339, "Nov", 2, 21, 25, "exception_hierarchy.pdf")

[(2356, 'Dec', 11, 11, 50, 'add_colab_link.py'),
 (164519, 'Dec', 28, 17, 59, 'basics.ipynb'),
 (164477, 'Nov', 5, 19, 21, 'basics.ipynb.orig'),
 (115587, 'Dec', 11, 11, 50, 'bayes.ipynb'),
 (4096, 'Nov', 29, 13, 7, '_build'),
 (198820, 'Dec', 11, 11, 50, 'clustering.ipynb'),
 (6647, 'Dec', 11, 12, 20, 'conf.py'),
 (41828, 'Nov', 28, 13, 26, 'example_figure2.png'),
 (125079, 'Nov', 28, 13, 26, 'example_figure2.xcf'),
 (24139, 'Nov', 28, 12, 3, 'example_figure.png'),
 (650, 'Nov', 28, 12, 3, 'example_figure.py'),
 (25399, 'Nov', 2, 21, 25, 'exception_hierarchy.pdf'),
 (43632, 'Nov', 2, 22, 5, 'exception_hierarchy.png'),
 (24366, 'Nov', 2, 21, 26, 'exception_hierarchy.svg'),
 (72095, 'Oct', 3, 17, 36, 'extra.ipynb'),
 (1207075, 'Nov', 28, 16, 2, 'face.png'),
 (897, 'Nov', 12, 10, 59, 'generate_contents.py'),
 (4096, 'Dec', 27, 13, 55, '.git'),
 (19, 'Dec', 10, 10, 24, '.gitignore'),
 (890349, 'Dec', 11, 11, 50, 'image_processing.ipynb'),
 (689, 'Dec', 10, 10, 28, 'index.rst'),
 (5254, 'N

In [85]:
#exercise03

In [15]:
def red_green_blue(filename="src/rgb.txt"):
    tulos = []
    with open(filename, "r") as f:
        next(f) # skipataan eka turha rivi
        for x in range(754):
            try:
                string = f.readline()
                mo = re.search(r'(\d+)\s+(\d+)\s+(\d+)\s+(.*)', string)
                teksti = mo.group(0)
                osien_lista = teksti.split(sep=None)
                if len(osien_lista) > 4:
                    osien_lista[3] = osien_lista[3] + " " + osien_lista[4]
                tulosstring = ("\t".join(osien_lista[0:3]))
                tulosstring = tulosstring + "\t" + osien_lista[3]
                tulos.append(tulosstring)
            except Exception as err:
                    pass
    return tulos

In [87]:
#red_green_blue('rgb.txt')

In [88]:
##exercise04

In [16]:
##NO TOCAR  
def word_frequencies(filename):
    with open(filename, "r") as f:
        string = f.readline()
        strSplit = string.split(" ")
        L = string.split(" ")
        Lbuena = []
        for item in L:
            Lbuena.append(item)
            dictOfWords = dict.fromkeys(Lbuena , len(item))
    return dictOfWords

In [17]:
def word_frequencies(filename):
    # Creating empty result and final lists.
    result = []
    final = []
    d = {}
    # Reading the file.
    with open(filename, "r") as f:
        # Splitting the lines into words.
        for line in f:
            for word in line.split():
                wordtemp = word.strip("""!"#$%&'()*,-./:;?@[]_""")#.lower()
                result.append(wordtemp)
        # Puts words and their count into dict.
        for word in result:
            if word not in final:
                final.append(word)
        for x in final:
            d[x] = result.count(x)
    return d

In [18]:
#pruebis
def word_frequencies(filename):
    # Creating empty result and final lists.
    result = []
    final = []
    d = {}
    # Reading the file.
    with open(filename, "r") as f:
        # Splitting the lines into words.
        for line in f:
            for word in line.split():
                wordtemp = word.strip("""!"#$%&'()*,-./:;?@[]_""")#.lower()
                result.append(wordtemp)
        # Puts words and their count into dict.
        for word in result:
            if word not in final:
                final.append(word)
        for x in final:
            d[x] = len(x)
    return d

In [92]:
#word_frequencies('alice.txt')

In [21]:
result = []
final = []
d = {}
# Reading the file.
with open('alice.txt', "r") as f:
    # Splitting the lines into words.
    for line in f:
        for word in line.split():
            wordtemp = word.strip("""!"#$%&'()*,-./:;?@[]_""")#.lower()
            result.append(wordtemp)
    # Puts words and their count into dict.
    for word in result:
        if word not in final:
            final.append(word)
    for x in final:
        d[x] = result.count(x)
#d

In [24]:
result = []
final = []
d = {}
# Reading the file.
with open('alice.txt', "r") as f:
    # Splitting the lines into words.
    for line in f:
        for word in line.split():
            wordtemp = word.strip("""!"#$%&'()*,-./:;?@[]_""")#.lower()
            result.append(wordtemp)
    # Puts words and their count into dict.
    for word in result:
        if word not in final:
            final.append(word)
    for x in final:
        d[x] = len(x)
d

{'The': 3,
 'Project': 7,
 'Gutenberg': 9,
 'EBook': 5,
 'of': 2,
 'Alice': 5,
 'in': 2,
 'Wonderland': 10,
 'by': 2,
 'Lewis': 5,
 'Carroll': 7,
 'This': 4,
 'eBook': 5,
 'is': 2,
 'for': 3,
 'the': 3,
 'use': 3,
 'anyone': 6,
 'anywhere': 8,
 'at': 2,
 'no': 2,
 'cost': 4,
 'and': 3,
 'with': 4,
 'almost': 6,
 'restrictions': 12,
 'whatsoever': 10,
 'You': 3,
 'may': 3,
 'copy': 4,
 'it': 2,
 'give': 4,
 'away': 4,
 'or': 2,
 're-use': 6,
 'under': 5,
 'terms': 5,
 'License': 7,
 'included': 8,
 'this': 4,
 'online': 6,
 'www.gutenberg.org': 17,
 'Title': 5,
 'Author': 6,
 'Illustrator': 11,
 'Gordon': 6,
 'Robinson': 8,
 'Release': 7,
 'Date': 4,
 'August': 6,
 '12': 2,
 '2006': 4,
 '19033': 5,
 'Language': 8,
 'English': 7,
 'Character': 9,
 'set': 3,
 'encoding': 8,
 'ASCII': 5,
 '': 0,
 'START': 5,
 'OF': 2,
 'THIS': 4,
 'PROJECT': 7,
 'GUTENBERG': 9,
 'EBOOK': 5,
 'ALICE': 5,
 'IN': 2,
 'WONDERLAND': 10,
 'Produced': 8,
 'Jason': 5,
 'Isbell': 6,
 'Irma': 4,
 'Spehar': 6,
 'Onli

In [94]:
##exercise05

In [95]:
def summary(filename):
    L=[]
    #reading the file
    with open(filename, "r") as f:
        L = []
        for line in f:
            try:
                n = float(line)
                L.append(n)
            except:
                pass
        Sum = sum(L)
        Average = statistics.mean(L)
        Stddev = statistics.stdev(L)
    return print("Sum:", Sum, "Average:", Average, "Stddev:", Stddev)

In [96]:
import statistics

with open('example.txt', "r") as f:
    sample = []
    for line in f:
        try:
            n = float(line)
            sample.append(n)
        except:
            pass
    Sum = sum(sample)
    Average = statistics.mean(sample)
    Stddev = statistics.stdev(sample)
print("Sum:", Sum, "Average:", Average, "Stddev:", Stddev)

Sum: 51.4 Average: 10.28 Stddev: 8.90460554993875


In [97]:
summary('example2.txt')

Sum: 5446.2 Average: 1815.4 Stddev: 3124.2940450604196


In [98]:
##example06

In [99]:
def file_count(filename):
    words_ = []
    words = []
    char = 0
    with open(filename, "r") as f:
        lines = f.readlines()
        for line in lines:
            words_ += line.split()
            words += line
        for word in words:
            char += len(word)
    return (len(lines), len(words_), char)
    #return (lines, words, characters)

In [100]:
file_count('test.txt')

(8, 105, 647)

In [101]:
wordList = []
final = []
Llines = []
d = {}
with open('test.txt', "r") as f:
    ##number of lines
    for line in f:
        Llines.append(line)
    lines = len(Llines)
lines

8

In [102]:
Lbuena = []
with open('test.txt', "r") as f:
    for line in f:
        for word in line.split():
            Lbuena.append(word)
        words = len(Lbuena)
words

105

In [103]:
Lchar = []
with open('test.txt', "r") as f:
    for line in f:
        for word in line:
            for char in word:
                Lchar.append(char)
    characters = len(Lchar)
characters

647

In [104]:
##example07

In [105]:
def file_extensions(filename):
    l = []
    d = {}
    with open(filename, "r") as f:
        lines = f.readlines()
    for line in lines:
        line = line.strip()
        if "." in line:
            two = line.rsplit(".", 1)
            end = two[1]
            if end in d:
                d[end].append(line)
            else:
                d[end]=[line]
        else:
            l.append(line)
    return (l,d)

In [106]:
file_extensions('filenames.txt')

(['test'],
 {'txt': ['file1.txt', 'file2.txt'],
  'pdf': ['mydocument.pdf'],
  'gz': ['archive.tar.gz']})

In [107]:
l = []
file_extension = []
files = []
d = {}
with open('filenames.txt', "r") as f:
    lines = f.readlines()
for line in lines:
    line = line.strip()
    if "." in line:
        two = line.rsplit(".", 1)
        end = two[1]
        if end in d:
            d[end].append(line)
        else:
            d[end]=[line]
    else:
        l.append(line)
(l, d)

(['test'],
 {'txt': ['file1.txt', 'file2.txt'],
  'pdf': ['mydocument.pdf'],
  'gz': ['archive.tar.gz']})

In [108]:
##erxercise 08

In [109]:
class Prepend(object):
    # Add the methods of the class here
    def __init__(self, char):
        self.char = char
    #create the write function
    def write(cls, char):
        return cls(char)

In [110]:
##DEFINITIVO
class Prepend(object):
    # Add the methods of the class here
    def __init__(self, char):
        self.start = char
    #create the write function
    def write(self, s):
        return print(self.start + s)

In [111]:
p = Prepend("+++ ")
print(p.start)
p.write("Hello")
#+++ Hello

+++ 
+++ Hello


In [112]:
from datetime import date
   
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age       
    # a class method to create a Person object by birth year.
    @classmethod
    def fromBirthYear(cls, name, year):
        return cls(name, date.today().year - year)  
    def otro(name, year, s):
        return print(name, date.today().year - year, s)       
    # a static method to check if a Person is adult or not.
    @staticmethod
    def isAdult(age):
        return age > 18   

person1 = Person('mayank', 21)
person2 = Person.fromBirthYear('mayank', 1996)   
print (person1.age)
print (person2.age)
person1.otro()
# print the result
print (Person.isAdult(22))

21
25


TypeError: otro() missing 2 required positional arguments: 'year' and 's'

In [31]:
class MyClass:
    """A simple example class"""
    i = 12345

    def f(self):
        return 'hello world'

In [41]:
##INHERITANCE

In [42]:
class B(object):
    def f(self):
        print("Executing B.f")
    def g(self):
        print("Executing B.g")

class C(B):
    def g(self):
        print("Executing C.g")

x=C()
x.f() # inherited from B
x.g() # overridden by C

Executing B.f
Executing C.g


In [43]:
##exercise 09

In [163]:
class Rational(object):
    """rational number class"""
    def __init__(self, num, denom):
        "This initialises an instance of type ClassName"
        self.numerator = num
        self.denominator = denom
    def __str__(self):
        return '%s/%s' % (self.numerator, self.denominator)
    def __mul__(a, b):
        """Multiply two rational numbers."""
        return Rational(a.numerator * b.numerator, a.denominator * b.denominator)
    def __truediv__(a, b):
        """Divide two rational numbers."""
        return Rational(a.numerator * b.denominator, a.denominator * b.numerator)
    def __add__(a, b):
        """Divide two rational numbers."""
        return Rational(a.numerator * b.denominator + b.numerator * a.denominator, a.denominator * b.denominator)
    def __sub__(a, b):
        """Divide two rational numbers."""
        return Rational(a.numerator * b.denominator - b.numerator * a.denominator, a.denominator * b.denominator)
    def __eq__(a, b):
        """Divide two rational numbers."""
        return a.numerator == b.numerator and a.denominator == b.denominator
    def __gt__(self,y):
        if self.numerator*y.denominator > self.denominator*y.numerator:
            return True
        else: 
            return False
    def __lt__(self,y):
        if self.numerator*y.denominator < self.denominator*y.numerator:
            return True
        else: 
            return False

In [164]:
r1=Rational(1,4)
r2=Rational(2,3)
print(r1)
print(r2)
print(r1*r2)
print(r1/r2)
print(r1+r2)
print(r1-r2)
print(Rational(1,2) == Rational(2,4))
print(Rational(1,2) > Rational(2,4))
print(Rational(1,2) < Rational(2,4))

1/4
2/3
2/12
3/8
11/12
-5/12
False
False
True


In [166]:
##solucion
class Rational(object):
    def __init__(self, n, d):
        self.n = n
        self.d = d
    def __str__(self):
        return "%i/%i" % (self.n, self.d)
    def __repr__(self):
        return "Rational(%i, %i)" % (self.n, self.d)
    def __mul__(self, r2):
        a = self.n * r2.n
        b = self.d * r2.d
        return Rational(a,b)
    def __truediv__(self, r2):
        a = self.n * r2.d
        b = self.d * r2.n
        return Rational(a,b)
    def __add__(self, r2):
        d1 = self.d
        d2 = r2.d
        a = self.n * d2 + r2.n * d1
        b = d1 * d2
        return Rational(a, b)
    def __sub__(self, r2):
        d1 = self.d
        d2 = r2.d
        a = self.n * d2 - r2.n * d1
        b = d1 * d2
        return Rational(a, b)
    def __eq__(self, r2):
        return self.n * r2.d == self.d *r2.n
    def __lt__(self, r2):
        return self.n * r2.d < self.d *r2.n
    def __gt__(self, r2):
        return self.n * r2.d > self.d *r2.n
def main():
    r1=Rational(1,4)
    r2=Rational(2,3)
    print(r1)
    print(r2)
    print(r1*r2)
    print(r1/r2)
    print(r1+r2)
    print(r1-r2)
    print(Rational(1,2) == Rational(2,4))
    print(Rational(1,2) > Rational(2,4))
    print(Rational(1,2) < Rational(2,4))
if __name__ == "__main__":
    main()

In [167]:
##Exceptions

In [168]:
L=[1,2,3]
try:
	print(L[3])
except IndexError:
	print("Index does not exist")

Index does not exist


In [170]:
def compute_average(L):
	n=len(L)
	s=sum(L)
	return float(s)/n #error is noticed here!!!
mylist=[]
while True:
	try:
		x=float(input("Give a number (non-number quits): "))
		mylist.append(x) 
	except ValueError:
		break
try:
	average=compute_average(mylist)
	print("Average is", average)
except ZeroDivisionError:
	#the error is handled here
	if len(mylist)==0:
		print("Tried to compute the average of empty list of numbers")
	else:
		print("Something strange happened!")

Average is 8.083333333333334


In [171]:
###too general exceptions

In [172]:
import sys
s=input("Give a number: ")
s=s[:-1] # strip the \n character from the end
try:
    x=int(s)
    sys.stdout.wr1te(f"You entered {x}\n")
except Exception:
    print("You didn’t enter a number")

You didn’t enter a number


In [173]:
##exercise 10

In [208]:
def extract_numbers(string):
    l = []
    result = []
    l = string.split()
    for item in l:
        try:
            result.append(int(item))
        except ValueError:
            try:
                result.append(float(item))
            except ValueError:
                pass
    return result

In [209]:
print(extract_numbers("abd 123 1.2 test 13.2 -1"))
#[123, 1.2, 13.2, -1]

[123, 1.2, 13.2, -1]


In [210]:
extract_numbers("abd 123 1.2 test 13.2 -1")

[123, 1.2, 13.2, -1]

In [9]:
#NUMPY
import numpy as np

In [3]:
## creation of arrays
np.array([1,2,3]) #one dimensional array

array([1, 2, 3])

In [5]:
np.array([[1,2,3],[4,5,6]]) #two dimensional array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # three dimensional array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
np.zeros((3,4)) # null array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
np.ones((2,3))  # array filled with ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.full((2,3), fill_value=7) # fill array with the ssame value

array([[7, 7, 7],
       [7, 7, 7]])

In [12]:
np.empty((2,4)) # empty array

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.06915806e-320, 0.00000000e+000,
        1.66880539e-308]])

In [14]:
np.eye(5, dtype=int) # idendity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [16]:
np.arange(0,10,2) # the arnage is similar to the range function, but creates an array instead

array([0, 2, 4, 6, 8])

In [17]:
np.linspace(0, np.pi, 5) # evenly spaced range with 5 elements; for non integer arrays

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [18]:
### array of random elements
np.random.random((3,4)) #elements are uniformly distributed from half-open interval `0.0, 1.0)

array([[0.48397666, 0.54537716, 0.88389225, 0.24650913],
       [0.51927985, 0.50503515, 0.78844673, 0.38521645],
       [0.40628817, 0.83596412, 0.70995795, 0.98760212]])

In [19]:
np.random.normal(0,1,(3,4)) #elements are normally distributed with mean 0 and standard deviation 1

array([[-0.0350308 ,  0.66727521, -0.19547854, -0.80876014],
       [ 0.89528518,  0.0549497 , -2.55221714, -1.08239726],
       [ 0.42697415, -0.38612716, -0.20688345, -1.71392207]])

In [20]:
np.random.normal(0,1,(3,4)) #elements are normally distributed with mean 0 and standard deviation 1

array([[-0.5332854 , -0.54335159,  0.93090619, -1.16107317],
       [-0.66022258, -0.56869097,  0.97680999, -0.70830748],
       [ 0.07633731, -0.10809703,  0.13655605,  0.28296515]])

In [21]:
np.random.seed(0)
print(np.random.randint(0, 100, 10))
print(np.random.normal(0, 1, 10))

[44 47 64 67 67  9 83 21 36 87]
[ 1.26611853 -0.50587654  2.54520078  1.08081191  0.48431215  0.57914048
 -0.18158257  1.41020463 -0.37447169  0.27519832]


In [22]:
new_generator = np.random.RandomState(seed = 123) #RandomState is a class, so we give the seed to its constructor
new_generator.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [84]:
## array types and attributes
def info(name, a):
	print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size} and dtype {a.dtype}:")
	print(a)

In [24]:
b=np.array([[1,2,3],[4,5,6]])
info("b", b)

b has dim 2, shape (2, 3), size 6 and dtype int32


In [25]:
b=np.array([[1,2,3],[4,5,6]])
info("b", b)

b has dim 2, shape (2, 3), size 6 and dtype int32


In [26]:
d=np.array([[1,2,3,4]])
info("d",d)

d has dim 2, shape (1, 4), size 4 and dtype int32


In [27]:
## indexing and reshaping
a=np.array([1,4,2,7,9,5])
print(a[1])
print(a[-2])

4
9


In [28]:
####for multidimensional arrays
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b[1,2]) #row indez 1, column index 2
print(b[0,1]) #row index 0, column index -1

[[1 2 3]
 [4 5 6]]
6
2


In [29]:
#as with lists, modification through indexing is possible
b[0,0] = 10
print(b)

[[10  2  3]
 [ 4  5  6]]


In [30]:
#as with lists, modification through indexing is possible
b[0,0] = 10
print(b)

[[10  2  3]
 [ 4  5  6]]


In [31]:
### slicing
print(a)
print(a[1:3])
print(a[::-1]) #reverses the array

[1 4 2 7 9 5]
[4 2]
[5 9 7 2 4 1]


In [32]:
print(b)
print(b[:,0])
print(b[0,:])
print(b[:,1:])

[[10  2  3]
 [ 4  5  6]]
[10  4]
[10  2  3]
[[2 3]
 [5 6]]


In [33]:
b[:,1:] = 7
print(b)

[[10  7  7]
 [ 4  7  7]]


In [34]:
print(b[:,0]) # first column
print(b[1,:]) # second row

[10  4]
[4 7 7]


In [35]:
## reshaping
a=np.arange(9)
anew=a.reshape(3,3)
info("new", anew) 
info("a", a)

new has dim 2, shape (3, 3), size 9 and dtype int32
a has dim 1, shape (9,), size 9 and dtype int32


In [36]:
d=np.arange(4) #1d array
dr=d.reshape(1,4) #row vector
dc=d.reshape(4,1) #column vector
info("d", d)
info("dr", dr)
info("dc", dc)

d has dim 1, shape (4,), size 4 and dtype int32
dr has dim 2, shape (1, 4), size 4 and dtype int32
dc has dim 2, shape (4, 1), size 4 and dtype int32


In [37]:
info("d", d)
info("drow", d[:,np.newaxis])
info("drow", d[np.newaxis, :])
info("dcol", d[:,np.newaxis])

d has dim 1, shape (4,), size 4 and dtype int32
drow has dim 2, shape (4, 1), size 4 and dtype int32
drow has dim 2, shape (1, 4), size 4 and dtype int32
dcol has dim 2, shape (4, 1), size 4 and dtype int32


In [38]:
## exercise 11

In [39]:
def get_rows(a):
    rows = []
    for row in a:
        #a = array[i]
        rows.append(row)
    return rows
def get_columns(a):
    columns = []
    b = a.T 
    for column in b:
        #a = array[i]
        columns.append(column)
    return columns

In [40]:
a = np.array([[5, 0, 3, 3], [7, 9, 3, 5], [2, 4, 7, 6], [8, 8, 1, 6]])
get_rows(a)
#[array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]


[array([5, 0, 3, 3]),
 array([7, 9, 3, 5]),
 array([2, 4, 7, 6]),
 array([8, 8, 1, 6])]

In [41]:
get_columns(a)
#[array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]

[array([5, 7, 2, 8]),
 array([0, 9, 4, 8]),
 array([3, 3, 7, 1]),
 array([3, 5, 6, 6])]

In [42]:
## array concatenation, splitting and stacking
a=np.arange(2)
b=np.arange(2,5)
print(f"a has shape {a.shape}: {a}")
print(f"b has shape {b.shape}: {b}")
np.concatenate((a,b))  # concatenating 1d arrays

a has shape (2,): [0 1]
b has shape (3,): [2 3 4]


array([0, 1, 2, 3, 4])

In [43]:
c=np.arange(1,5).reshape(2,2)
print(f"c has shape {c.shape}:", c, sep="\n")
np.concatenate((c,c))   # concatenating 2d arrays

c has shape (2, 2):
[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [44]:
np.concatenate((c,c), axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [45]:
"""for concatenating a column to na existing array, first you'll need to reshape it """
print("New row:")
print(np.concatenate((c,a.reshape(1,2))))
print("New column:")
print(np.concatenate((c,a.reshape(2,1)), axis=1))

New row:
[[1 2]
 [3 4]
 [0 1]]
New column:
[[1 2 0]
 [3 4 1]]


In [46]:
"""use stack to create higher dimensional arrays from lower dimensional arrays"""
np.stack((b,b))

array([[2, 3, 4],
       [2, 3, 4]])

In [47]:
np.stack((b,b), axis=1) #stack as columns

array([[2, 2],
       [3, 3],
       [4, 4]])

In [48]:
"""the inverse fo concatenate is split"""
d=np.arange(12).reshape(6,2)
print("d:")
print(d)
d1,d2 = np.split(d, 2)
print("d1:")
print(d1)
print("d2:")
print(d2)

d:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
d1:
[[0 1]
 [2 3]
 [4 5]]
d2:
[[ 6  7]
 [ 8  9]
 [10 11]]


In [49]:
d=np.arange(12).reshape(2,6)
print("d:")
print(d)
parts=np.split(d, (2,3,5), axis=1)
for i, p in enumerate(parts):
    print("part %i:" % i)
    print(p)

d:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
part 0:
[[0 1]
 [6 7]]
part 1:
[[2]
 [8]]
part 2:
[[ 3  4]
 [ 9 10]]
part 3:
[[ 5]
 [11]]


In [50]:
## exercise 12

In [51]:
def get_row_vectors(a):
    rows = []
    for row in a:
        #a = array[i]
        rows.append(row)
    rows_t = tuple(rows)
    return rows
def get_column_vectors(a):
    columns = []
    b = a.T
    for column in b:
        #a = array[i]
        columns.append(column)
    columns_t = tuple(columns)
    return columns

In [52]:
def get_row_vectors(a):
    b = a.shape[0]
    c= np.split(a, b, axis =0)    
    return c
def get_column_vectors(a):
    b = a.shape[1]
    c= np.split(a, b, axis = 1)    
    return c

In [53]:
np.random.seed(0)
a=np.random.randint(0,10, (4,4))
print("a:", a)
print("Row vectors:", get_row_vectors(a))
print("Column vectors:", get_column_vectors(a))

a: [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
Row vectors: [array([[5, 0, 3, 3]]), array([[7, 9, 3, 5]]), array([[2, 4, 7, 6]]), array([[8, 8, 1, 6]])]
Column vectors: [array([[5],
       [7],
       [2],
       [8]]), array([[0],
       [9],
       [4],
       [8]]), array([[3],
       [3],
       [7],
       [1]]), array([[3],
       [5],
       [6],
       [6]])]


In [54]:
a = np.array([[5, 0, 3], [3, 7, 9]])

In [55]:
get_row_vectors(a)
#Row vectors:
#[array([[5, 0, 3]]), array([[3, 7, 9]])]


[array([[5, 0, 3]]), array([[3, 7, 9]])]

In [56]:
get_column_vectors(a)
#Column vectors:
#[array([[5],[3]]),
 #array([[0], [7]]),
 #array([[3],[9]])]

[array([[5],
        [3]]),
 array([[0],
        [7]]),
 array([[3],
        [9]])]

In [57]:
##exercise 13
#Do this using the eye and concatenate functions of NumPy and array slicing.
import numpy as np

In [58]:
def diamond(number):
    #base array
    if number != 1:
        a = np.eye(number, dtype=int)
        b = a.T
        c = a[::-1][:,:-1]
        d = b[::-1][:,1-a.shape[0]:]
        concat01 = np.concatenate((c,a), axis = 1)
        concat02 = np.concatenate((b,d), axis = 1)[1:,:]
        concat = np.concatenate((concat01, concat02))
    elif number == 1:
        concat = np.eye(number, dtype=int)
    return concat

In [59]:
print(diamond(5))
#[[0 0 1 0 0]
#[0 1 0 1 0]
#[1 0 0 0 1]
#[0 1 0 1 0]
#[0 0 1 0 0]]


[[0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 1 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 1 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0]]


In [60]:
#cuadra para 2
a = np.eye(2, dtype=int)
b = a.T
c = a[::-1][:,:-1]
d = b[::-1][:,1-a.shape[0]:]
concat01 = np.concatenate((c,a), axis = 1)
concat02 = np.concatenate((b,d), axis = 1)[1:,:]
concat = np.concatenate((concat01, concat02))
concat

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [61]:
a = np.eye(3, dtype=int)
b = a.T
c = a[::-1][:,:-1]
d = b[::-1][:,1-a.shape[0]:]
concat01 = np.concatenate((c,a), axis = 1)
concat02 = np.concatenate((b,d), axis = 1)[1:,:]
concat = np.concatenate((concat01, concat02))
concat

array([[0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0]])

In [62]:
##Fast computation using interval functions
L=[1, 5.2, "ab"]
L2=[]
for x in L:
    L2.append(x*2)
print(L2)

[2, 10.4, 'abab']


In [63]:
a=np.array([2.1, 5.0, 17.2])
a2=a*2
print(a2)

[ 4.2 10.  34.4]


In [64]:
b=np.array([-1, 3.2, 2.4])
print(-a**2 * b)

[   4.41   -80.    -710.016]


In [65]:
print(np.abs(b))
print(np.cos(b))
print(np.exp(b))
print(np.log2(np.abs(b)))

[1.  3.2 2.4]
[ 0.54030231 -0.99829478 -0.73739372]
[ 0.36787944 24.5325302  11.02317638]
[0.         1.67807191 1.26303441]


In [66]:
#aggregations: maxi, min, sum, mean, standard deviation...
np.random.seed(0)
a=np.random.randint(-100, 100, (4,5))
print(a)
print(f"Minimum: {a.min()}, maximum: {a.max()}")
print(f"Sum: {a.sum()}")
print(f"Mean: {a.mean()}, standard deviation: {a.std()}")

[[ 72 -53  17  92 -33]
 [ 95   3 -91 -79 -64]
 [-13 -30 -12  40 -42]
 [ 93 -61 -13  74 -12]]
Minimum: -91, maximum: 95
Sum: -17
Mean: -0.85, standard deviation: 58.39886557117355


In [67]:
np.random.seed(9)
b=np.random.randint(0, 10, (3,4))
print(b)
print("Column sums:", b.sum(axis=0))
print("Row sums:", b.sum(axis=1))

[[5 6 8 6]
 [1 6 4 8]
 [1 8 5 1]]
Column sums: [ 7 20 17 15]
Row sums: [25 19 15]


In [68]:
a=np.arange(1000)
%timeit np.sum(a)

3.85 µs ± 163 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [69]:
%timeit sum(a)

68.2 µs ± 1.21 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [70]:
##exercise 14

In [71]:
def vector_lengths(a):
    number = a.shape[0]
    squared = np.square(a)    
    added = squared.sum(axis=1)
    length = np.sqrt(added)
    reshaped_length = length.reshape(number,)
    return reshaped_length

In [72]:
np.random.seed(9)
b = np.random.randint(0, 10, (3,4))
vector_lengths(b)

array([12.68857754, 10.81665383,  9.53939201])

In [73]:
##exercise 15
#result in degrees, not radiants
import numpy as np 
import scipy.linalg

In [74]:
def vector_angles(a,b):
    x = scipy.linalg.norm(a, 2, axis = 1)
    y = scipy.linalg.norm(b, 2, axis = 1)
    angle = np.arccos( np.clip( (np.dot(a,b) / (x * y)), -1, 1 ) )
    degrees = np.degrees(angle)
    return degrees

In [75]:
def vector_angles(a,b):
    x = np.sqrt(np.sum(np.square(a),axis=1))
    y = np.sqrt(np.sum(np.square(b),axis=1))
    tmp = np.sum(a * b,axis=1) / (x * y)
    angle = np.arccos( np.clip( tmp, -1.0, 1.0 ) )
    degrees = np.degrees(angle)
    return degrees

In [76]:
np.random.seed(4)
a = np.random.randint(0, 10, (3,3))
b = np.random.randint(0, 10, (3,3))
vector_angles(a,b)

array([36.61616347, 27.65948589, 40.25390571])

In [77]:
## model solution
def vector_angles(X, Y):
    ip = np.sum(X*Y, axis=1)
    Xlen = scipy.linalg.norm(X, 2, axis=1)
    Ylen = scipy.linalg.norm(Y, 2, axis=1)
    temp=ip/(Xlen*Ylen)
    temp = np.clip(temp, -1.0, 1.0)
    result =  np.arccos(temp) / np.pi * 180
    return result

In [78]:
## broadcasting
np.arange(3) + np.array([4])

array([4, 5, 6])

In [79]:
np.arange(3) + 4

array([4, 5, 6])

In [80]:
a=np.full((3,3), 5)
b=np.arange(3)
print("a:", a, sep="\n")
print("b:", b)
print("a+b:", a+b, sep="\n")
##boradcasted to the array np.array([[0, 1, 2],
       #[0, 1, 2],
       #[0, 1, 2]])

a:
[[5 5 5]
 [5 5 5]
 [5 5 5]]
b: [0 1 2]
a+b:
[[5 6 7]
 [5 6 7]
 [5 6 7]]


In [86]:
a=np.arange(3)
b=np.arange(3).reshape((3,1))
info("a", a)
info("b", b)
info("a+b", a+b)

a has dim 1, shape (3,), size 3 and dtype int32:
[0 1 2]
b has dim 2, shape (3, 1), size 3 and dtype int32:
[[0]
 [1]
 [2]]
a+b has dim 2, shape (3, 3), size 9 and dtype int32:
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [85]:
broadcasted_a, broadcasted_b = np.broadcast_arrays(a,b)
info("broadcasted_a", broadcasted_a)
info("broadcasted_b", broadcasted_b)

broadcasted_a has dim 2, shape (3, 3), size 9 and dtype int32:
[[0 1 2]
 [0 1 2]
 [0 1 2]]
broadcasted_b has dim 2, shape (3, 3), size 9 and dtype int32:
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [87]:
a=np.array([1,2,3])
b=np.array([4,5])
try:
    a+b                 # This does not work since it violates the rule 3 above.
except ValueError as e:
    import sys
    print(e, file=sys.stderr)

operands could not be broadcast together with shapes (3,) (2,) 


## exercise 16

In [113]:
def multiplication_table(number):
    a = np.arange(number)[np.newaxis]
    b = a.transpose()
    result = a*b
    return result

In [ ]:
print(multiplication_table(5))
#[[0 0 0 0]
# [0 1 2 3]
# [0 2 4 6]
# [0 3 6 9]]